### ISSUE TITLE
Time Formatting

### ISSUE THREAD

**Issue by sfnis** [TobiasUr/FlightMemoryExporter#1]
**Describe the bug**

Exported Flights are in "American format" , for example 08:15 instead of 20:15. 
This is also removes leading "1"s before the number format.  

**To Reproduce**
Export Flights, open in Excel.

I tried changing the formatting of the timestamp in Excel, no luck.  I changed my region and time format to UK, still the same results.  

![image](https://github.com/TobiasUr/FlightMemoryExporter/assets/44121087/bbf2bcbe-3388-4c0e-8414-428ea9a9f6e1)

**Comment by sfnis** [comment]
Actually, as far as I can tell, there are no 4 digit times exported at all.  12/11/10 are all truncated.

**Comment by TobiasUr** [comment]
Should be fixed in the latest release.
