### ISSUE TITLE
Time Formatting  Departure Column

### ISSUE THREAD

**Issue by sfnis** [TobiasUr/FlightMemoryExporter#2]
Thanks for fixing the Arrival Column, Departures column has the same issue.

![image](https://github.com/TobiasUr/FlightMemoryExporter/assets/44121087/5b0d806f-94c1-4688-a81e-9cbf5b45fdd8)

Also the Compiled EXE is getting flagged as a virus in Windows.  

![image](https://github.com/TobiasUr/FlightMemoryExporter/assets/44121087/6f6be791-748a-431f-b681-75499e385131)

**Comment by TobiasUr** [comment]
Fixed the arrival time and tried to package the file differently. For me it isn't getting flagged, but I don't know how it will work for other people.
